#!/usr/bin/env python3
"""
Linear (least-squares) unmixing on a sample network.

This module implements the linear formulation described in Appendix A of the funmixer
preprint. Where :class:`~funmixer.network_unmixer.SampleNetworkUnmixer` penalises *relative*
differences between predicted and observed concentrations (a convex surrogate for the
log-ratio misfit), this module penalises *absolute* differences. That choice is appropriate
when the tracer has low log-variance and it turns the whole problem into a linear system.

The forward model
-----------------
The observation at site ``i`` is a flux-weighted mixture of the source concentrations of every
sub-basin upstream of (and including) ``i``::

    d = M c,        M_ij = Theta_ij * alpha_{j->i} * q_j / Q_i

where ``Theta`` is the path matrix of the sample network with self-edges, ``q_j`` is the
material flux generated by sub-basin ``j``, ``Q_i = sum_j Theta_ij q_j`` is the total flux
passing site ``i``, and ``alpha_{j->i} = exp(-sum k*L)`` is the first-order decay accumulated
along the path from ``j`` to ``i``. Decay is applied to the tracer flux only and never to the
total flux, matching :func:`~funmixer.network_unmixer.forward_model`.

Why this is exactly soluble
---------------------------
funmixer defines exactly one sub-basin per sample site, so ``M`` is square (n x n). Ordered
topologically (upstream to downstream) it is **lower triangular with strictly positive
diagonal** ``M_ii = q_i / Q_i``, and is therefore always invertible. Two consequences:

1. At ``lambda = 0`` the problem is not really least-squares at all -- it has an exact,
   zero-residual solution ``c = M^-1 d``. There is no pseudo-inverse ambiguity, and weighted
   (GLS) variants collapse to the same estimator, so "the estimator used when unconstrained"
   is unambiguous. The inverse has a sparse closed form::

       c_i = ( Q_i d_i - sum_{p in direct upstream nbrs of i} alpha_p Q_p d_p ) / q_i

   i.e. "tracer flux out, minus tracer flux in, over own flux".
2. The non-negativity constraint bites *exactly* when ``Q_i d_i < sum_p alpha_p Q_p d_p`` --
   when a site carries less tracer flux than its own tributaries deliver. That is precisely
   where the method breaks down, and it is directly checkable via
   :attr:`LinearFunmixerSolution.unconstrained_preds`.

The per-node noise amplification of the inversion is ``1 / M_ii = Q_i / q_i``. A sample taken
just downstream of another, with little incremental drainage area between them, has a large
amplification factor and will be poorly resolved. This -- the disparity in *sub-basin areas* --
is the real control on whether the linear approach is usable for a given network, and it is
reported as :attr:`LinearFunmixerSolution.amplification`.

Regularization
--------------
Optionally we penalise the variance of ``c``, i.e. deviations of ``c`` from its *own* mean::

    minimize  (M c - d)^T C_d^-1 (M c - d)  +  lambda ||P c||^2      subject to  c >= 0

(the misfit term is ``||M c - d||^2`` when the solve is unweighted)

with ``P = I - (1/n) 1 1^T`` the centering projector, so that ``||P c||^2 = sum_i (c_i -
c_bar)^2 = n * var(c)``. Note lambda therefore weights the *sum* of squared deviations rather
than their mean, so a factor of ``n`` is absorbed into it. Note also this differs deliberately
from
:class:`SampleNetworkUnmixer`, which is forced by convexity to shrink towards the mean
*observation*; the linear form has no such constraint and can shrink towards the mean *model*.

A solution is guaranteed for every ``lambda >= 0``: the Hessian is ``2(M^T M + lambda P)``, and
although ``P`` alone is only positive semi-definite (its null space is ``span{1}``), ``M^T M``
is positive definite because ``M`` is invertible. The objective is therefore strictly convex,
giving a unique global minimiser, and it stays unique under ``c >= 0``. Regularization strictly
improves the conditioning, so ``lambda > 0`` is always better behaved than ``lambda = 0``.
Uniqueness does rest on ``M`` being invertible -- ``lambda P`` could not rescue a singular
``M`` on its own.

Error propagation
-----------------
Because ``||P c||^2`` is homogeneous in ``c``, the estimator carries **no constant offset** and
is purely linear in the data::

    c_hat  = R d,     R = (M^T M + lambda P)^-1 M^T
    C_c    = R C_d R^T       (covariance of the recovered source concentrations)
    C_dhat = M C_c M^T       (covariance of the modelled observations)

At ``lambda = 0`` this reduces to ``M^-1 C_d M^-T`` exactly, so the regularized and
unregularized cases share a single code path. Likewise the modelled-observation covariance
reduces to ``C_d`` itself at ``lambda = 0``, since the fit is exact there.

At ``lambda = 0`` the estimator is unbiased and ``C_c`` is the complete error. It also equals
``(M^T C_d^-1 M)^-1``, the Cramer-Rao lower bound, so the unregularized inversion is an
efficient estimator and no weighting can improve on it.

Once ``lambda > 0`` the estimator is **biased**, and two different covariances become relevant.
Both are reported:

* ``upstream_covariance``: the *propagated* (sampling) covariance ``R C_d R^T``. This answers
  "if I repeated the measurements, how would my estimate scatter?" It is exactly the linear
  propagation of ``C_d`` through the estimator actually used -- but it **shrinks as lambda
  grows**, because a more heavily damped estimator is more stable while being more wrong. Used
  alone at large lambda it badly understates the true error.
* ``upstream_posterior_covariance``: ``(M^T C_d^-1 M + lambda P)^-1``, the Bayesian posterior
  covariance obtained by reading the penalty as a prior. This accounts for what the damping
  costs as well as what it stabilises, and is the more honest error bar to quote at
  ``lambda > 0``. The two are related exactly by::

      R C_d R^T = (M^T C_d^-1 M + lambda P)^-1 - lambda A^-1 P A^-1,   A = M^T C_d^-1 M + lambda P

  so the propagated covariance is always the smaller of the two, and they coincide at
  ``lambda = 0``.

The remaining, unquantifiable piece is the bias itself,
``bias = -lambda A^-1 P c_true``, which needs the unknown ``c_true``. As a proxy we report the
resolution matrix ``R M`` (the identity at ``lambda = 0``, degrading as ``lambda`` grows) and
its trace, the effective number of degrees of freedom.

References
----------
These are standard results in discrete linear inverse theory; the notation below follows the
first two.

* Menke, W., *Geophysical Data Analysis: Discrete Inverse Theory*. Weighted least squares,
  damped least squares, and the two results used most directly here: for any linear estimator
  ``m_est = G^-g d`` the model covariance is ``C_m = G^-g C_d G^-g^T``, and the model
  resolution matrix is ``R = G^-g G``.
* Aster, R., Borchers, B. and Thurber, C., *Parameter Estimation and Inverse Problems*.
  Tikhonov regularization, the L-curve, resolution, and the bias-variance decomposition of the
  regularized solution -- i.e. why the propagated covariance is not the whole error.
* Tarantola, A. (2005), *Inverse Problem Theory and Methods for Model Parameter Estimation*,
  SIAM. The linear-Gaussian case, where the posterior covariance is
  ``(G^T C_d^-1 G + C_m^-1)^-1``; this is the source of `upstream_posterior_covariance`.
* Hoerl, A. E. and Kennard, R. W. (1970), "Ridge Regression: Biased Estimation for
  Nonorthogonal Problems", *Technometrics* 12(1), 55-67. The original bias-variance argument
  for penalised estimators.
* Hansen, P. C. (1998), *Rank-Deficient and Discrete Ill-Posed Problems*, SIAM. Filter factors,
  the L-curve, and general-form (seminorm) Tikhonov regularization -- the case here, since the
  penalty operator ``P`` is singular. The uniqueness condition for general-form Tikhonov is
  that the null spaces of the forward and penalty operators intersect only at zero, which
  holds here because ``M`` is invertible. See also Elden, L. (1977), "Algorithms for the
  regularization of ill-conditioned least squares problems", *BIT* 17, 134-145.
* Golub, G. H. and Van Loan, C. F., *Matrix Computations*, for the numerical treatment of
  generalised least squares via whitening, and of Tikhonov problems via augmented systems.
"""

import time
import warnings
from dataclasses import dataclass
from typing import Dict, List, Optional, Tuple, Union

import cvxpy as cp
import networkx as nx
import numpy as np
import numpy.typing as npt

from .network_unmixer import (
    SOLVERS,
    ElementData,
    ExportRateData,
    RateConstantData,
    SampleNode,
    nx_get_downstream_node,
    nx_topological_sort_with_data,
)

FloatArray = npt.NDArray[np.float64]

# A node is treated as clamped by the c >= 0 constraint when its unconstrained estimate falls
# below this (in mean-normalised units, where a typical concentration is 1).
CLAMP_TOLERANCE: float = 0.0

# Relative tolerance for the sanity check that CVXPY agrees with the analytical estimator on
# problems where no constraint is active. This is deliberately loose: interior-point solvers
# converge to ~1e-8, which an ill-conditioned mixing matrix amplifies by cond(M). A genuine
# mismatch between the two formulations would show up at order 1, not near this threshold.
ESTIMATOR_AGREEMENT_TOLERANCE: float = 1e-4

# Covariance input given as a bare number is interpreted as a relative error in *percent*,
# matching the `relative_error` convention of SampleNetworkUnmixer.solve_montecarlo.
DataCovariance = Union[float, int, ElementData, FloatArray, None]


@dataclass
class LinearFunmixerSolution:
    """
    Results of a :class:`LinearSampleNetworkUnmixer` run.

    The first seven fields mirror :class:`~funmixer.network_unmixer.FunmixerSolution` so that
    this object is a drop-in replacement for downstream plotting helpers. The remainder are
    specific to the linear formulation.

    Attributes:
        objective_value: The value of the (normalised-space) objective at the solution.
        solver_name: Name of the solver that CVXPY used.
        total_time: Wall-clock time for the whole solve, in seconds.
        solve_time: Solver-reported solve time, in seconds.
        setup_time: Solver-reported setup time, in seconds.
        downstream_preds: Predicted concentration at each sample site, in the input units.
        upstream_preds: Recovered source concentration for each sub-basin, in the input units.
        node_order: Topological ordering of the sample sites. This is the row/column ordering
            of every matrix below, and of any array-valued input.
        regularization_strength: The value of lambda used.
        weighted: Whether the misfit was weighted by the inverse data covariance.
        upstream_covariance: (n, n) *propagated* covariance of `upstream_preds`, in
            (input units)^2, or None if no `data_covariance` was supplied. Equal to
            `R C_d R^T`: the linear propagation of the data covariance through the estimator
            actually used. Exact, but it shrinks as lambda grows and so understates the true
            error at large lambda -- see `upstream_posterior_covariance`.
        upstream_std: Square root of the diagonal of `upstream_covariance`, per site.
        upstream_posterior_covariance: (n, n) Bayesian posterior covariance
            `(M^T C_d^-1 M + lambda P)^-1`, in (input units)^2. Available only for a weighted
            solve with `data_covariance` supplied, since it needs `C_d^-1`. This accounts for
            the cost of the damping as well as its stabilising effect, and is the more honest
            error bar to quote when lambda > 0. Identical to `upstream_covariance` at
            lambda = 0, and always at least as large.
        upstream_posterior_std: Square root of the diagonal of
            `upstream_posterior_covariance`, per site.
        downstream_covariance: (n, n) covariance of `downstream_preds`, in (input units)^2, or
            None. Equal to `M C_c M^T`; at lambda = 0 this is exactly `data_covariance`.
        downstream_std: Square root of the diagonal of `downstream_covariance`, per site.
        resolution_matrix: (n, n) resolution matrix `R M`. The identity at lambda = 0.
        effective_dof: `trace(R M)`, the effective number of degrees of freedom. Equal to n at
            lambda = 0 and decreasing as lambda grows.
        unconstrained_preds: The raw estimate `R d` before the c >= 0 constraint is applied, in
            the input units. Negative entries here show where, and by how much, the linear
            model fails.
        clamped_nodes: Sites whose unconstrained estimate was negative. If this is empty the
            returned estimator is exactly linear and the propagated covariances are exact.
        amplification: Per-site noise amplification `Q_i / q_i` of the inversion.
        condition_number: Condition number of the mixing matrix `M`.
        residual_norm: `||M c - d||_2` in normalised space. Zero at lambda = 0 with no clamping.
    """

    objective_value: float
    solver_name: str
    total_time: float
    solve_time: Optional[float]
    setup_time: Optional[float]
    downstream_preds: ElementData
    upstream_preds: ElementData
    node_order: List[str]
    regularization_strength: float
    weighted: bool
    unconstrained_preds: ElementData
    clamped_nodes: List[str]
    amplification: ElementData
    condition_number: float
    residual_norm: float
    upstream_covariance: Optional[FloatArray] = None
    upstream_std: Optional[ElementData] = None
    upstream_posterior_covariance: Optional[FloatArray] = None
    upstream_posterior_std: Optional[ElementData] = None
    downstream_covariance: Optional[FloatArray] = None
    downstream_std: Optional[ElementData] = None
    resolution_matrix: Optional[FloatArray] = None
    effective_dof: Optional[float] = None


class LinearSampleNetworkUnmixer:
    """
    Unmix a network of concentration observations using a linear (least-squares) formulation.

    This is the Appendix A counterpart to :class:`~funmixer.network_unmixer.SampleNetworkUnmixer`:
    it penalises absolute rather than relative misfit, which makes the forward model an exactly
    invertible matrix and admits closed-form error propagation. See the module docstring for the
    mathematics.

    The API deliberately mirrors :class:`SampleNetworkUnmixer`. In particular ``solve``,
    ``get_misfit`` and ``get_roughness`` have compatible signatures, so
    :func:`~funmixer.network_unmixer.plot_sweep_of_regularizer_strength` works on this class
    unchanged.

    Note:
        ``regularization_strength`` is **not** comparable between the two solvers. This one
        weights a *squared* penalty on deviations from the mean *model*; the non-linear solver
        weights an unsquared norm of deviations from the mean *observation*. Because the data
        are mean-normalised internally, lambda here is dimensionless and does transfer between
        elements and datasets.
    """

    def __init__(
        self,
        sample_network: nx.DiGraph,
        use_regularization: bool = True,
        rate_constants: Optional[RateConstantData] = None,
    ) -> None:
        """
        Initialise the LinearSampleNetworkUnmixer.

        Args:
            sample_network: The sample network (see `get_sample_graph`).
            use_regularization: Whether to include the model-variance penalty. If True, a
                `regularization_strength` must be supplied to `solve`.
            rate_constants: Per-site first-order decay constants k [L^-1]. Sites omitted from
                the dict default to 0 (conservative behaviour). Can be overridden per-solve.
        """
        self.sample_network = sample_network
        self.node_order: List[str] = [
            name for name, _ in nx_topological_sort_with_data(sample_network)
        ]
        self._index: Dict[str, int] = {name: i for i, name in enumerate(self.node_order)}
        self._n: int = len(self.node_order)
        if self._n == 0:
            raise ValueError("Cannot unmix an empty sample network.")

        # Sub-basin areas, normalised by their mean purely for numerical conditioning. This
        # mirrors the `rltv_area` semantics of SampleNetworkUnmixer, but is kept in a local
        # array: the `SampleNode` attributes are shared scratch space used by `forward_model`
        # and `SampleNetworkUnmixer`, and writing to them would corrupt a live problem built
        # on the same graph.
        areas = np.array([self._node_data(name).area for name in self.node_order], dtype=np.float64)
        if np.any(areas <= 0):
            raise ValueError("All sub-basin areas must be strictly positive.")
        self._rltv_area: FloatArray = areas / float(np.mean(areas))

        self._use_regularization = use_regularization
        self._rate_constants: Optional[RateConstantData] = rate_constants

        # State from the most recent solve, used by get_misfit / get_roughness / get_estimator.
        self._M: Optional[FloatArray] = None
        self._R: Optional[FloatArray] = None
        self._c_norm: Optional[FloatArray] = None
        self._d_norm: Optional[FloatArray] = None
        self._M_solver: Optional[FloatArray] = None
        self._d_solver: Optional[FloatArray] = None
        self._weighted: bool = False

        # The compiled CVXPY problem, and the mixing matrix it was compiled for.
        self._problem: Optional[cp.Problem] = None
        self._problem_M: Optional[FloatArray] = None

    # ------------------------------------------------------------------ helpers

    def _node_data(self, name: str) -> SampleNode:
        return self.sample_network.nodes[name]["data"]

    def _centering_projector(self) -> FloatArray:
        """P = I - (1/n) 1 1^T, the projector onto the space of mean-zero vectors."""
        n = self._n
        return np.eye(n) - np.ones((n, n)) / n

    def _ensure_problem(self, M: FloatArray) -> None:
        """
        Build (or reuse) the CVXPY problem for a given mixing matrix.

        `d` and `lambda` are Parameters, so Monte Carlo draws, sweeps over lambda and sweeps
        over elements all reuse a single compiled problem -- the DPP intent of
        `SampleNetworkUnmixer`. `M`, by contrast, is embedded as a constant. Making it a
        Parameter is technically DPP-compliant but puts n^2 parameters into the problem, which
        CVXPY canonicalises far more slowly than it recompiles. `M` only changes when the
        export rates or rate constants change, so rebuilding on that event is much cheaper.

        The objective uses *squared* norms, unlike `SampleNetworkUnmixer._build_problem`. That
        is what makes the estimator linear, and is not optional here.
        """
        if self._problem is not None and np.array_equal(M, self._problem_M):
            return

        n = self._n
        self._c_var = cp.Variable(n, nonneg=True)
        self._d_param = cp.Parameter(n)
        self._lam_param = cp.Parameter(nonneg=True)

        objective = cp.sum_squares(M @ self._c_var - self._d_param)
        if self._use_regularization:
            # ||P c||^2, i.e. the variance of the model about its own mean.
            objective += self._lam_param * cp.sum_squares(self._c_var - cp.sum(self._c_var) / n)

        self._problem = cp.Problem(cp.Minimize(objective))
        assert self._problem.is_dcp(dpp=True)
        self._problem_M = M.copy()

    # ---------------------------------------------------------- forward operator

    def _build_mixing_matrix(
        self,
        export_rates: Optional[ExportRateData],
        rate_constants: Optional[RateConstantData],
    ) -> Tuple[FloatArray, FloatArray, FloatArray]:
        """
        Build the mixing matrix `M`, and the total (`Q`) and own (`q`) fluxes of each site.

        This performs exactly the topological sweep of
        :func:`~funmixer.network_unmixer.forward_model`, but propagates a *row of coefficients*
        instead of a scalar concentration. It is therefore identical to running the forward
        model once per basis vector, and `M @ c == forward_model(network, c)` to machine
        precision.

        Returns:
            (M, total_flux, own_flux), all ordered by `self.node_order`.
        """
        n = self._n
        M = np.zeros((n, n), dtype=np.float64)
        tracer_rows = np.zeros((n, n), dtype=np.float64)
        total_flux = np.zeros(n, dtype=np.float64)
        own_flux = np.zeros(n, dtype=np.float64)

        for name in self.node_order:
            i = self._index[name]
            rate = export_rates[name] if export_rates else 1.0
            flux = rate * self._rltv_area[i]

            own_flux[i] = flux
            # Contributions from upstream have already been accumulated into these, because
            # `node_order` is a topological sort.
            total_flux[i] += flux
            tracer_rows[i, i] += flux

            M[i, :] = tracer_rows[i, :] / total_flux[i]

            downstream = nx_get_downstream_node(self.sample_network, name)
            if downstream is not None:
                j = self._index[downstream]
                length = self.sample_network[name][downstream]["length"]
                k = rate_constants.get(name, 0.0) if rate_constants else 0.0
                alpha = float(np.exp(-k * length))
                # NB: decay applies to the tracer flux only, never to the total flux.
                total_flux[j] += total_flux[i]
                tracer_rows[j, :] += tracer_rows[i, :] * alpha

        return M, total_flux, own_flux

    def _solve_unregularized(
        self,
        d_norm: FloatArray,
        total_flux: FloatArray,
        own_flux: FloatArray,
        rate_constants: Optional[RateConstantData],
    ) -> FloatArray:
        """
        Exact O(n + edges) solution of `M c = d` using the sparse closed form for `M^-1`.

        `c_i = (Q_i d_i - sum_p alpha_p Q_p d_p) / q_i`, i.e. the tracer flux leaving site `i`
        minus the tracer flux delivered by its immediate upstream neighbours, divided by the
        flux that site `i` itself generates.
        """
        tracer_flux = total_flux * d_norm
        c = np.empty(self._n, dtype=np.float64)
        for name in self.node_order:
            i = self._index[name]
            accumulated = tracer_flux[i]
            for upstream in self.sample_network.predecessors(name):
                length = self.sample_network[upstream][name]["length"]
                k = rate_constants.get(upstream, 0.0) if rate_constants else 0.0
                accumulated -= float(np.exp(-k * length)) * tracer_flux[self._index[upstream]]
            c[i] = accumulated / own_flux[i]
        return c

    def _whitener(self, covariance_norm: FloatArray) -> FloatArray:
        """
        Build `L^-1`, where `C = L L^T`, so that `L^-1 e` has identity covariance.

        Pre-multiplying the system by this turns generalised least squares into ordinary
        least squares: minimising `||L^-1(Mc - d)||^2` is minimising the Mahalanobis misfit
        `(Mc - d)^T C^-1 (Mc - d)`.
        """
        n = self._n
        diagonal = np.diag(covariance_norm)
        if np.allclose(covariance_norm, np.diag(diagonal)):
            # The common case. Much cheaper, and avoids a needless factorisation.
            if np.any(diagonal <= 0):
                raise ValueError(
                    "data_covariance has a zero or negative variance, so it cannot be used as "
                    "a weighting. Pass weighted=False, or give every site a positive variance."
                )
            return np.diag(1.0 / np.sqrt(diagonal))
        try:
            factor = np.linalg.cholesky(covariance_norm)
        except np.linalg.LinAlgError as exc:
            raise ValueError(
                "data_covariance must be positive definite to be used as a weighting. "
                "Pass weighted=False to fall back to an unweighted inversion."
            ) from exc
        return np.linalg.solve(factor, np.eye(n))

    def _build_estimator(
        self, M: FloatArray, lam: float, whitener: Optional[FloatArray]
    ) -> FloatArray:
        """
        Build the linear estimator `R` such that `c_hat = R d`.

        Unweighted, this is `R = (M^T M + lambda P)^-1 M^T`. Weighted by `W = C_d^-1` it is
        the generalised-least-squares estimator `R = (M^T W M + lambda P)^-1 M^T W`, which we
        form via the whitening transform `M_w = L^-1 M` so there is only one code path.

        At lambda = 0 this is exactly `M^-1` **whatever the weighting**: `M` is square and
        invertible, so `(M^T W M)^-1 M^T W = M^-1 W^-1 M^-T M^T W = M^-1`. The unregularized
        fit is exact and passes through every observation, so there is nothing for a weighting
        to trade off. Weighting only changes the answer once `lambda > 0`.
        """
        n = self._n
        if lam == 0.0:
            return np.linalg.solve(M, np.eye(n))
        M_w = M if whitener is None else whitener @ M
        # M_w^T M_w + lambda P is symmetric positive definite: M_w^T M_w is PD because both
        # M and the whitener are invertible, and lambda P is PSD.
        normal_matrix = M_w.T @ M_w + lam * self._centering_projector()
        adjoint = M_w.T if whitener is None else M_w.T @ whitener
        return np.linalg.solve(normal_matrix, adjoint)

    # ------------------------------------------------------------- data handling

    def _observations_to_array(self, observation_data: ElementData) -> FloatArray:
        missing = set(self.node_order) - set(observation_data)
        if missing:
            raise ValueError(f"No observation supplied for site(s): {sorted(missing)}")
        unknown = set(observation_data) - set(self.node_order)
        if unknown:
            raise ValueError(f"Observation supplied for unknown site(s): {sorted(unknown)}")
        return np.array([observation_data[name] for name in self.node_order], dtype=np.float64)

    def _coerce_data_covariance(
        self, data_covariance: DataCovariance, d: FloatArray
    ) -> Optional[FloatArray]:
        """
        Normalise the many accepted spellings of `data_covariance` into an (n, n) matrix.

        Accepted forms, all in the *input* units of the observations:
            None                -- skip error propagation.
            a bare number       -- a relative error in percent, so sigma_i = d_i * value / 100.
                                   This matches `SampleNetworkUnmixer.solve_montecarlo`'s
                                   `relative_error`, so the two are directly comparable.
            dict                -- per-site standard deviations.
            1-D array (n,)      -- per-site standard deviations, in `node_order`.
            2-D array (n, n)    -- a full covariance matrix, in `node_order`.
        """
        if data_covariance is None:
            return None

        n = self._n
        if isinstance(data_covariance, (float, int)) and not isinstance(data_covariance, bool):
            sigma = d * float(data_covariance) / 100.0
            return np.diag(sigma**2)

        if isinstance(data_covariance, dict):
            missing = set(self.node_order) - set(data_covariance)
            if missing:
                raise ValueError(f"No data_covariance entry for site(s): {sorted(missing)}")
            sigma = np.array(
                [float(data_covariance[name]) for name in self.node_order], dtype=np.float64
            )
            return np.diag(sigma**2)

        array = np.asarray(data_covariance, dtype=np.float64)
        if array.ndim == 1:
            if array.shape != (n,):
                raise ValueError(f"1-D data_covariance must have shape ({n},), got {array.shape}")
            return np.diag(array**2)
        if array.ndim == 2:
            if array.shape != (n, n):
                raise ValueError(
                    f"2-D data_covariance must have shape ({n}, {n}), got {array.shape}"
                )
            return array
        raise ValueError("data_covariance must be a number, dict, 1-D array or 2-D array.")

    def _to_dict(self, values: FloatArray) -> ElementData:
        return {name: float(values[self._index[name]]) for name in self.node_order}

    # -------------------------------------------------------------------- solve

    def solve(
        self,
        observation_data: ElementData,
        export_rates: Optional[ExportRateData] = None,
        rate_constants: Optional[RateConstantData] = None,
        regularization_strength: Optional[float] = None,
        data_covariance: DataCovariance = None,
        weighted: bool = True,
        solver: str = "clarabel",
        compute_resolution: bool = True,
        warm_start: bool = False,
    ) -> LinearFunmixerSolution:
        """
        Solve the linear unmixing problem.

        The observations are divided by their arithmetic mean before solving and the results
        multiplied back afterwards. The problem is homogeneous, so this has no effect on the
        answer -- it exists purely to keep the numbers near unity for the solver, and to make
        `regularization_strength` dimensionless and comparable across datasets.

        Args:
            observation_data: Observed concentration at each sample site.
            export_rates: Export rate for each sub-catchment. Defaults to 1 everywhere (i.e.
                homogeneous erosion/runoff).
            rate_constants: Per-site first-order decay constants k [L^-1]. Defaults to those
                given at construction, or to 0 (conservative) for omitted sites.
            regularization_strength: lambda, weighting the squared penalty on the variance of
                the model. Required if the problem was built with `use_regularization=True`.
                Not comparable to the equivalent argument of `SampleNetworkUnmixer.solve`.
            data_covariance: Uncertainty on the observations, enabling closed-form error
                propagation. A bare number is read as a relative error in percent; see
                `_coerce_data_covariance` for the other accepted forms. If None, the covariance
                fields of the result are left as None.
            weighted: Whether to weight the misfit by the inverse data covariance, i.e. to
                solve generalised rather than ordinary least squares. Has an effect only when
                `data_covariance` is supplied *and* `regularization_strength` is non-zero --
                see `_build_estimator` for why weighting cannot change an unregularized
                solution. Strongly recommended whenever the observations span a wide range and
                the errors are proportional, which makes them badly heteroscedastic.
            solver: CVXPY solver to use (default "clarabel").
            compute_resolution: Whether to compute the resolution matrix and effective degrees
                of freedom. Costs one O(n^3) matrix product; set False for large networks.
            warm_start: Seed the solver from the previous solution.

        Returns:
            A :class:`LinearFunmixerSolution`.

        Raises:
            Exception: If regularization is enabled but no strength was supplied.
            ValueError: If the observations do not match the sites in the network.

        Note:
            When no site is clamped by the `c >= 0` constraint, the returned point estimate is
            the analytical estimator `R d` exactly, not the solver's approximation to it. This
            guarantees that the estimate and the propagated covariances come from the same
            linear operator, which is what makes the error propagation meaningful. When sites
            *are* clamped the estimator is no longer linear; the covariance is still reported
            (it assumes the unconstrained estimator) but a warning is issued.
        """
        if self._use_regularization and regularization_strength is None:
            raise Exception("WARNING: Regularizer terms present but no strength assigned.")
        if solver not in SOLVERS:
            raise Exception(
                f"Solver {solver} not supported. Supported solvers are {list(SOLVERS.keys())}"
            )

        lam = float(regularization_strength) if self._use_regularization else 0.0
        if lam < 0:
            raise ValueError("regularization_strength must be non-negative.")
        if rate_constants is None:
            rate_constants = self._rate_constants

        start_time = time.time()

        d = self._observations_to_array(observation_data)
        d_bar = float(np.mean(d))
        if d_bar <= 0:
            raise ValueError("Mean observed concentration must be positive.")
        d_norm = d / d_bar

        M, total_flux, own_flux = self._build_mixing_matrix(export_rates, rate_constants)

        # Weighting. The covariance is scaled into normalised space so that the whitened
        # residuals are dimensionless, which in turn keeps lambda dimensionless: the objective
        # trades a chi-squared-like misfit against the variance of the model.
        C_d = self._coerce_data_covariance(data_covariance, d)
        is_weighted = weighted and C_d is not None
        whitener: Optional[FloatArray] = None
        if is_weighted:
            assert C_d is not None
            whitener = self._whitener(C_d / d_bar**2)

        # The unconstrained estimate. At lambda = 0 the sparse closed form is both exact and
        # O(n); otherwise we go via R, which we need for the covariance anyway.
        need_estimator = (C_d is not None) or compute_resolution or lam > 0.0
        R: Optional[FloatArray] = (
            self._build_estimator(M, lam, whitener) if need_estimator else None
        )
        if lam == 0.0:
            c_unconstrained = self._solve_unregularized(
                d_norm, total_flux, own_flux, rate_constants
            )
        else:
            assert R is not None
            c_unconstrained = R @ d_norm

        # Always solve via CVXPY: it supplies the solver statistics, and it is the only route
        # to a correct answer when the c >= 0 constraint is active. The whitened system is
        # handed to it so that it minimises the same objective as the analytical estimator.
        M_solver = M if whitener is None else whitener @ M
        d_solver = d_norm if whitener is None else whitener @ d_norm
        self._ensure_problem(M_solver)
        self._d_param.value = d_solver
        self._lam_param.value = lam
        objective_value = self._problem.solve(**SOLVERS[solver], warm_start=warm_start)
        if self._problem.status != "optimal":
            warnings.warn(
                f"CVXPY returned status '{self._problem.status}'.", RuntimeWarning, stacklevel=2
            )

        clamped_mask = c_unconstrained < CLAMP_TOLERANCE
        clamped_nodes = [name for name in self.node_order if clamped_mask[self._index[name]]]

        if not clamped_nodes:
            # The objective is strictly convex, so `c_unconstrained` is *the* unconstrained
            # global minimiser. It is also feasible, hence a fortiori the constrained optimum.
            # Return it exactly rather than the solver's approximation, so that the point
            # estimate and the propagated covariance share one estimator.
            c_norm = c_unconstrained
            solver_c = np.asarray(self._c_var.value, dtype=np.float64)
            scale = max(float(np.max(np.abs(c_norm))), 1.0)
            discrepancy = float(np.max(np.abs(c_norm - solver_c))) / scale
            if discrepancy > ESTIMATOR_AGREEMENT_TOLERANCE:
                warnings.warn(
                    f"Analytical and CVXPY solutions differ by {discrepancy:.3e} (relative) "
                    "despite no active constraints. The mixing matrix is probably badly "
                    f"conditioned (cond = {np.linalg.cond(M):.3e}), which amplifies solver "
                    "tolerance; treat the recovered concentrations with caution.",
                    RuntimeWarning,
                    stacklevel=2,
                )
        else:
            c_norm = np.asarray(self._c_var.value, dtype=np.float64)
            warnings.warn(
                f"{len(clamped_nodes)} site(s) clamped at the lower bound "
                f"({clamped_nodes if len(clamped_nodes) <= 10 else clamped_nodes[:10] + ['...']}). "
                "The constrained estimator is not linear in the data, so any propagated "
                "covariance assumes the unconstrained estimator and will overstate uncertainty "
                "at these sites.",
                UserWarning,
                stacklevel=2,
            )

        d_pred_norm = M @ c_norm
        residual_norm = float(np.linalg.norm(d_pred_norm - d_norm))

        # Error propagation. The estimator maps observations to concentrations in *any*
        # consistent scaling, so the mean-normalisation cancels exactly and we can work
        # directly in the input units: C_c = R C_d R^T, C_dpred = M C_c M^T.
        upstream_covariance: Optional[FloatArray] = None
        upstream_std: Optional[ElementData] = None
        downstream_covariance: Optional[FloatArray] = None
        downstream_std: Optional[ElementData] = None
        upstream_posterior_covariance: Optional[FloatArray] = None
        upstream_posterior_std: Optional[ElementData] = None
        if C_d is not None:
            assert R is not None
            upstream_covariance = _symmetrise(R @ C_d @ R.T)
            downstream_covariance = _symmetrise(M @ upstream_covariance @ M.T)
            upstream_std = self._to_dict(np.sqrt(np.clip(np.diag(upstream_covariance), 0, None)))
            downstream_std = self._to_dict(
                np.sqrt(np.clip(np.diag(downstream_covariance), 0, None))
            )
            if is_weighted:
                # (M^T C_d^-1 M + lambda P)^-1, built from the whitened operator so it needs
                # no explicit inverse of C_d. M_solver is in normalised space, so the result
                # is scaled back into the input units by d_bar^2.
                normal_matrix = M_solver.T @ M_solver + lam * self._centering_projector()
                upstream_posterior_covariance = _symmetrise(
                    np.linalg.solve(normal_matrix, np.eye(self._n)) * d_bar**2
                )
                upstream_posterior_std = self._to_dict(
                    np.sqrt(np.clip(np.diag(upstream_posterior_covariance), 0, None))
                )

        resolution_matrix: Optional[FloatArray] = None
        effective_dof: Optional[float] = None
        if compute_resolution:
            assert R is not None
            resolution_matrix = R @ M
            effective_dof = float(np.trace(resolution_matrix))

        # Cache for get_misfit / get_roughness / get_estimator.
        self._M, self._R, self._c_norm, self._d_norm = M, R, c_norm, d_norm
        self._M_solver, self._d_solver, self._weighted = M_solver, d_solver, is_weighted

        return LinearFunmixerSolution(
            objective_value=float(objective_value),
            solver_name=self._problem.solver_stats.solver_name,
            total_time=time.time() - start_time,
            solve_time=self._problem.solver_stats.solve_time,
            setup_time=self._problem.solver_stats.setup_time,
            downstream_preds=self._to_dict(d_pred_norm * d_bar),
            upstream_preds=self._to_dict(c_norm * d_bar),
            node_order=list(self.node_order),
            regularization_strength=lam,
            weighted=is_weighted,
            unconstrained_preds=self._to_dict(c_unconstrained * d_bar),
            clamped_nodes=clamped_nodes,
            amplification=self._to_dict(total_flux / own_flux),
            condition_number=float(np.linalg.cond(M)),
            residual_norm=residual_norm,
            upstream_covariance=upstream_covariance,
            upstream_std=upstream_std,
            upstream_posterior_covariance=upstream_posterior_covariance,
            upstream_posterior_std=upstream_posterior_std,
            downstream_covariance=downstream_covariance,
            downstream_std=downstream_std,
            resolution_matrix=resolution_matrix,
            effective_dof=effective_dof,
        )

    # ------------------------------------------------------------- introspection

    def get_misfit(self) -> float:
        """
        The data misfit of the most recent solve, in normalised space.

        This is the quantity the objective actually minimises: `||M c - d||_2` for an
        unweighted solve, and the Mahalanobis norm `sqrt((Mc-d)^T C_d^-1 (Mc-d))` for a
        weighted one. The latter is a chi distance, so a well-fitting weighted solve gives
        roughly `sqrt(n)`.

        Together with `get_roughness`, this makes the class compatible with
        :func:`~funmixer.network_unmixer.plot_sweep_of_regularizer_strength`.
        """
        if self._M_solver is None or self._c_norm is None or self._d_solver is None:
            raise Exception("No solution available: call solve() first.")
        return float(np.linalg.norm(self._M_solver @ self._c_norm - self._d_solver))

    def get_roughness(self) -> float:
        """
        The model roughness `||P c||_2` of the most recent solve, in normalised space.

        This is the total deviation of the recovered concentrations from their own mean, the
        same quantity the regularization penalises.
        """
        if self._c_norm is None:
            raise Exception("No solution available: call solve() first.")
        return float(np.linalg.norm(self._c_norm - np.mean(self._c_norm)))

    def get_mixing_matrix(self) -> Tuple[FloatArray, List[str]]:
        """Return the mixing matrix `M` of the most recent solve, and its node ordering."""
        if self._M is None:
            raise Exception("No solution available: call solve() first.")
        return self._M, list(self.node_order)

    def get_estimator(self) -> Tuple[FloatArray, List[str]]:
        """
        Return the linear estimator `R` of the most recent solve, and its node ordering.

        `c = R d` holds in both normalised and input units. Users wanting to propagate their
        own uncertainties can use `C_c = R C_d R^T` and `C_dpred = M C_c M^T` directly.
        """
        if self._R is None:
            raise Exception(
                "No estimator available: call solve() first, with data_covariance set or "
                "compute_resolution=True."
            )
        return self._R, list(self.node_order)


def _symmetrise(matrix: FloatArray) -> FloatArray:
    """Remove the antisymmetric round-off that accumulates in triple matrix products."""
    return 0.5 * (matrix + matrix.T)
